name: release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  goreleaser_uploadDist:
    runs-on: ubuntu-18.04
    if: ${{ github.repository == gocq/go-cqhttp }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Dist
        uses: actions/checkout@v2
        with:
          repository: "gocq/distRepo"
          ref: main
          ssh-key: ${{ secrets.SSH_KEY }}
          path: upstream/distRepo
          submodules: recursive

      - name: Install packaging dependencies
        run: sudo apt-get install reprepro createrepo rpm

      - name: Set up GPG
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{secrets.SIGNING_KEY_FILE}}
          passphrase: ${{secrets.KEY_PASSPHRASE}}

      - name: Sign RPMS
        run: |
          cp scripts/rpmmacros ~/.rpmmacros
          rpmsign --addsign dist/*.rpm

      - name: Update Dist
        run: |
          chmod +x scripts/update_repo.sh
          ./scripts/update_repo.sh
